---
language: python
services:
  - docker
jobs:
  include:
    - name: "Install from Source Test - Debian"
      env: scenario=source
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible==2.9.6
  - pip install molecule[docker]>=3.0.0
  - pip install testinfra
  - pip install ansible-lint
  - pip install flake8
script:
  - molecule --version
  - ansible --version
  - molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
