---
- import_tasks: prerequisites/install-prerequisites.yml
  tags: nginx_prerequisites

- import_tasks: keys/apt-key.yml
  when:
    - ansible_os_family == "Debian"
    - nginx_install_from == "nginx_repository"
      or nginx_unit_enable
  tags: nginx_aptkey

- import_tasks: keys/rpm-key.yml
  when:
    - ansible_os_family == "RedHat"
      or ansible_os_family == "Suse"
    - nginx_install_from == "nginx_repository"
      or nginx_unit_enable
  tags: nginx_rpmkey

- name: "(Install: Debian/Ubuntu/CentOS/RedHat/FreeBSD) Install NGINX"
  block:

    - import_tasks: opensource/install-oss.yml
      tags: nginx_install_oss

    - import_tasks: conf/cleanup-config.yml
      when: nginx_cleanup_config | bool
      tags: nginx_cleanup_config

    - import_tasks: conf/upload-config.yml
      when: nginx_main_upload_enable
            or nginx_http_upload_enable
            or nginx_stream_upload_enable
            or nginx_html_upload_enable
            or nginx_ssl_upload_enable
      tags: nginx_upload_config

    - import_tasks: conf/template-config.yml
      when: nginx_main_template_enable
            or nginx_http_template_enable
            or nginx_stream_template_enable
      tags: nginx_template_config

    - import_tasks: conf/setup-status.yml
      when: nginx_status_enable | bool
      tags: nginx_setup_status

    - import_tasks: modules/install-modules.yml
      when: true in nginx_modules.values()
      tags: nginx_install_modules

    - import_tasks: conf/debug-output.yml
      when: nginx_debug_output | bool
      tags: nginx_debug_output

  when: nginx_enable | bool

- import_tasks: unit/install-unit.yml
  when: nginx_unit_enable | bool
  tags: nginx_install_unit

- import_tasks: conf/logrotate.yml
  when: nginx_logrotate_conf_enable | bool
  tags: nginx_logrotate_config
