---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-nginx-rtmp
  vars:
    nginx_debug_output: true

    nginx_modules:
      njs: true
      perl: true
      geoip: true
      image_filter: true
      rtmp: true
      xslt: true
