---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "Set repo if Debian"
      set_fact:
        version: "=1.17.8-1~{{ ansible_distribution_release }}"
      when: ansible_os_family == "Debian"
  roles:
    - role: ansible-role-nginx-rtmp
  vars:
    nginx_version: "{{ version }}"
