---
dependency:
  name: shell
  command: pip install python-nginx
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian-buster
    image: debian:buster-slim
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook_stable_push.yml
verifier:
  name: testinfra
  directory: ../common/test_stable_push
