---
- name: "(Setup: All OSs) Set NGINX Plus License State"
  set_fact:
    nginx_license_status: absent

- name: "(Setup: All OSs) Delete NGINX Plus License"
  file:
    path: /etc/ssl/nginx
    state: absent

- import_tasks: setup-bsd.yml
  when: ansible_os_family == "FreeBSD"

- import_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: setup-suse.yml
  when: ansible_os_family == "Suse"
